# Generated by Django 4.2.7 on 2025-05-08 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_collection', '0004_alter_scanresult_match_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='备注内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='data_collection.asset', verbose_name='资产')),
            ],
            options={
                'verbose_name': '资产备注',
                'verbose_name_plural': '资产备注列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
