# Generated by Django 4.2.7 on 2025-03-23 05:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_type', models.CharField(choices=[('sql_injection', 'SQL注入'), ('xss', 'XSS跨站脚本'), ('file_inclusion', '文件包含'), ('command_injection', '命令注入'), ('ssrf', 'SSRF服务器端请求伪造'), ('xxe', 'XXE外部实体注入'), ('other', '其他')], max_length=20, verbose_name='漏洞类型')),
                ('scan_type', models.CharField(choices=[('passive', '被动扫描'), ('active', '主动扫描')], max_length=10, verbose_name='扫描类型')),
                ('name', models.CharField(max_length=255, verbose_name='漏洞名称')),
                ('description', models.TextField(verbose_name='漏洞描述')),
                ('severity', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低'), ('info', '信息')], max_length=10, verbose_name='严重程度')),
                ('url', models.URLField(verbose_name='漏洞URL')),
                ('request', models.TextField(blank=True, null=True, verbose_name='请求数据')),
                ('response', models.TextField(blank=True, null=True, verbose_name='响应数据')),
                ('proof', models.TextField(verbose_name='漏洞证明')),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='扫描日期')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_scan_results', to='data_collection.asset', verbose_name='资产')),
            ],
            options={
                'verbose_name': '漏洞扫描结果',
                'verbose_name_plural': '漏洞扫描结果列表',
                'ordering': ['-scan_date'],
            },
        ),
    ]
