# Generated by Django 4.2.7 on 2025-05-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_scan', '0002_remove_scan_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnscanresult',
            name='parameter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='漏洞参数'),
        ),
        migrations.AddField(
            model_name='vulnscanresult',
            name='payload',
            field=models.TextField(blank=True, null=True, verbose_name='漏洞载荷'),
        ),
        migrations.AddField(
            model_name='vulnscanresult',
            name='vuln_detail',
            field=models.TextField(blank=True, null=True, verbose_name='漏洞详细信息'),
        ),
        migrations.AddField(
            model_name='vulnscanresult',
            name='vuln_subtype',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='漏洞子类型'),
        ),
    ]
