# Generated by Django 4.2.7 on 2025-05-08 04:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import report_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_collection', '0004_alter_scanresult_match_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='报告描述')),
                ('report_type', models.CharField(choices=[('asset', '资产报告'), ('vuln', '漏洞报告'), ('comprehensive', '综合报告')], max_length=20, verbose_name='报告类型')),
                ('report_file', models.FileField(blank=True, null=True, upload_to=report_management.models.report_file_path, verbose_name='报告文件')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='generating', max_length=20, verbose_name='状态')),
                ('status_message', models.TextField(blank=True, null=True, verbose_name='状态信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('assets', models.ManyToManyField(blank=True, related_name='reports', to='data_collection.asset', verbose_name='相关资产')),
            ],
            options={
                'verbose_name': '安全检测报告',
                'verbose_name_plural': '安全检测报告列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('template_file', models.FileField(upload_to='report_templates/', verbose_name='模板文件')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报告模板',
                'verbose_name_plural': '报告模板列表',
            },
        ),
        migrations.CreateModel(
            name='ReportGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='任务ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_task', to='report_management.report', verbose_name='关联报告')),
            ],
            options={
                'verbose_name': '报告生成任务',
                'verbose_name_plural': '报告生成任务列表',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_management.reporttemplate', verbose_name='使用模板'),
        ),
    ]
